AddSettings
JoeriGithub/Space-Game pull request #219
Opened 2024-05-22 16:32 UTC by AdilRamdjan

Added volume sliders for music and sound effects. And added mouse sensitivity to settings menu.

2024-05-22 19:37 UTC, Petervh1 requested changes

2024-05-22 19:37 UTC, Petervh1 commented on Assets/Prefabs/Menus/QuestSelectionScreen.prefab
revert deze file, tekst hier heeft inmiddels een nieuw font en dit zou dat terugdraaien.

2024-05-22 19:37 UTC, Petervh1 commented on Assets/Prefabs/PlayerPrefab.prefab
haalt 2.2k lines aan nieuwe features weg door gebrek aan pullen :/ wordt waarschijnlijk compleet reverten en opnieuw je changes maken.

2024-05-22 19:37 UTC, Petervh1 commented on Assets/Scenes/ShipScene.unity
wederom veel font changes die weg moeten

2024-05-22 19:40 UTC, AdilRamdjan commented on Assets/Prefabs/PlayerPrefab.prefab
Ik heb letterlijk een nieuwe pull gedaan voor die pr... idk waarom dat gebeurd...

2024-05-23 10:41 UTC, Petervh1 approved these changes

2024-05-23 10:42 UTC, merged