Add new enemey
JoeriGithub/Space-Game pull request #247
Opened 2024-05-27 18:29 UTC by Kikkerslijm410

Thomas plz check de enemy scripts
Joeri of Peter check de rest

2024-05-27 19:49 UTC, JoeriGithub approved these changes

2024-05-27 21:03 UTC, Petervh1 requested changes
Graag enum gebruiken ipv string, verder top!

2024-05-28 17:58 UTC, Thoopa approved these changes

2024-05-29 09:54 UTC, JoeriGithub approved these changes
het is wel enemy

2024-05-29 09:56 UTC, merged